### ISSUE TITLE
Railway in different layers

### ISSUE THREAD

**Issue by RailMapper** [hiddewie/OpenRailwayMap-vector#104]
Crossing ways railway=rail, layer=1 with railway=rail, layer=-1 are not visible well. See for example
<https://openrailwaymap.fly.dev/#view=17.33/51.043851/13.722931&style=standard>

Otherwise hovering the mentioned ways show which one is the upper or lower one. But this is not convenient. The current OpenRailwayMap (raster) should be the guide for the the visibility.

**Comment by hiddewie** [comment]
Thanks for the issue.

It seems that the order of the layers in https://github.com/hiddewie/OpenRailwayMap-vector/blob/a4c5dbf1f5bc3135f5e83e7d8843fe4272d2d491/proxy/js/styles.mjs#L1065 is not correct, the casing is always below the fill layers.

**Comment by hiddewie** [comment]
Fixed with #106
