### ISSUE TITLE
Missing SQL function `railway_speed_int_noconvert(text)`

### ISSUE THREAD

**Issue by wolfy1339** [hiddewie/OpenRailwayMap-vector#130]
In the commit https://github.com/hiddewie/OpenRailwayMap-vector/commit/d4622683351cc34045c9ba078fcd50bf55385fe7
the SQL function was removed, however there are still calls to that function that no longer exists.

```
martin-1  | [2024-10-30T00:12:51Z ERROR martin::srv::server] Unable to get tile 10/309/361 from railway_line_high: db error: ERROR: function railway_speed_int_noconvert(text) does not exist
martin-1  |     HINT: No function matches the given name and argument types. You might need to add explicit type casts.
```

The cause of this issue is because the `railway_direction_speed_limit(preferred_direction TEXT, speed TEXT, forward_speed TEXT, backward_speed TEXT)` function still calls `railway_speed_int_noconvert(text)`.
This happens because the `railway_direction_speed_limit()` function is called in the tile views:
https://github.com/hiddewie/OpenRailwayMap-vector/blob/9afcb1f00b91b7499160fd8495094b9299e64e81/import/sql/tile_views.sql#L51

**Comment by hiddewie** [comment]
Thanks for this issue, I missed it because locally my database still contained the functions from previous imports. I will make a fix.

We really need the integration tests solved (#86) so these kind of things are tested with a fresh database in CI, and preventing pull requests from being merged.
