### ISSUE TITLE
Signal boxes in buildings aren't rendered properly at levels <11.5

### ISSUE THREAD

**Issue by besentv** [hiddewie/OpenRailwayMap-vector#133]
Like the title says, two images as reference:

ORM:
![image](https://github.com/user-attachments/assets/2704d62d-8271-4f24-9abb-b2e66eb2e21b)

ORM-Vector:
![image](https://github.com/user-attachments/assets/6d654e91-c9ba-46e0-8ee9-4373eae8c90b)

**Comment by hiddewie** [comment]
Thanks for the issue. A fix will be implemented in  https://github.com/hiddewie/OpenRailwayMap-vector/pull/138
