### ISSUE TITLE
Electrification layer errors

### ISSUE THREAD

**Issue by besentv** [hiddewie/OpenRailwayMap-vector#134]
Observation: In ORM-Vector lines electrified with <750V are rendered as grey + non-electrified lines and lines without data are rendered black. 

![image](https://github.com/user-attachments/assets/948ac279-9c57-40f8-a2ce-50a903ee43f8)

Expectation: Render <750V as pink rose-ish and unknown as grey.

![image](https://github.com/user-attachments/assets/bdc523bf-06b6-482c-ae4b-7e7669545276)

**Comment by hiddewie** [comment]
Thanks for the issue. This is fixed in https://github.com/hiddewie/OpenRailwayMap-vector/pull/136

**Comment by hiddewie** [comment]
I also found that the future electrification dashes were not rendered correctly, fixed in https://github.com/hiddewie/OpenRailwayMap-vector/pull/137.
