### ISSUE TITLE
Signal DE-BOStrab:so5 isn't rendered.

### ISSUE THREAD

**Issue by besentv** [hiddewie/OpenRailwayMap-vector#155]
See: 

https://openrailwaymap.org/?style=signals&lat=49.43681514760021&lon=11.115936487913132&zoom=19

vs 

https://openrailwaymap.fly.dev/#view=17.76/49.436724/11.115358&style=signals

**Comment by hiddewie** [comment]
Thanks for the issue, this will be resolved with https://github.com/hiddewie/OpenRailwayMap-vector/pull/163
