### ISSUE TITLE
Signal DE-BOStrab:sh4 isn't rendered

### ISSUE THREAD

**Issue by besentv** [hiddewie/OpenRailwayMap-vector#156]
Example usage:

https://overpass-turbo.eu/s/1UPZ

More infos about this signal, here:
https://wiki.openstreetmap.org/wiki/DE:OpenRailwayMap/Tagging_Trams_in_Germany#L%C3%A4uten_(Sh_4)

**Comment by hiddewie** [comment]
Thanks for the issue.

The wiki https://wiki.openstreetmap.org/wiki/DE:OpenRailwayMap/Tagging_Trams_in_Germany#L%C3%A4uten_(Sh_4) is somewhat incorrect, the tag was documented as `railway:signal:main:form=sign` I will edit it to `railway:signal:ring:form=sign` like the OSM data.

**Comment by hiddewie** [comment]
Thanks, this will be implemented in https://github.com/hiddewie/OpenRailwayMap-vector/pull/165
