### ISSUE TITLE
Signal DE-ESO:bü2 isn't rendered

### ISSUE THREAD

**Issue by besentv** [hiddewie/OpenRailwayMap-vector#160]
Both normal and shortened versions aren't showing up.

## Normal:

ORM-v:
https://openrailwaymap.fly.dev/#view=14.56/49.49881/11.11281&style=signals

ORM:
![image](https://github.com/user-attachments/assets/90f275c5-a9cf-4623-bc9a-938c21fd1f38)

## Shortened:

ORM-v:
https://openrailwaymap.fly.dev/#view=16.8/49.410727/11.105465&style=signals

ORM:
![image](https://github.com/user-attachments/assets/84747e20-17e9-4967-879f-fb19060f4f61)

**Comment by hiddewie** [comment]
Thanks for the issue. There was a misconfiguration trying to render Bü4 as Bü2.

This will be fixed in https://github.com/hiddewie/OpenRailwayMap-vector/pull/167
