### ISSUE TITLE
Bad color contrast in dark mode

### ISSUE THREAD

**Issue by wolfy1339** [hiddewie/OpenRailwayMap-vector#175]
The header in the pop-up is hard to read when using dark mode
![image](https://github.com/user-attachments/assets/ec7dc04e-5df0-4a7d-8571-a6da359aeb17)

**Comment by hiddewie** [comment]
Thanks for the issue. 

Indeed, the popup has the style
```css
background: #fff;
```
hardcoded, it does not take the theme into account.

I will try to patch the library CSS with the theme colors to make it look in line with the rest of the page.

**Comment by hiddewie** [comment]
Should be fixed with https://github.com/hiddewie/OpenRailwayMap-vector/pull/176
