### ISSUE TITLE
Improve level crossings

### ISSUE THREAD

**Issue by hiddewie** [hiddewie/OpenRailwayMap-vector#44]
- Icon for lights
- Icon for bells?
- Improve icons
- Country specific?

**Comment by hiddewie** [comment]
https://github.com/hiddewie/OpenRailwayMap-vector/pull/48

**Comment by MatisseBE** [comment]
Could it be considered to show a level crossing's reference on the map, and not just in the pop-up? If anyone can help point me towards the right file, that would also be wonderful!! 

<img width="492" height="461" alt="Image" src="https://github.com/user-attachments/assets/92e5705f-3792-4046-a579-16e66e419c9e" />

**Comment by MatisseBE** [comment]
To a lesser extent, it might also be useful to bubble level crossings with the same reference. It allows us to bundle the icons and their reference, so it only needs to be rendered once. It looks a lot cleaner and removes any doubt there might be if two adjacent crossings are one or two level crossings. 

Some concepts below:

<img width="2577" height="2159" alt="Image" src="https://github.com/user-attachments/assets/308f07f8-a18b-452f-a896-7bce57fd4a7c" />

<img width="3736" height="1960" alt="Image" src="https://github.com/user-attachments/assets/4f9d6f3c-a5d2-4601-b3ab-5221c0792d32" />

**Comment by MatisseBE** [comment]
Lastly, I really wanted to display LX at a lower zoom level but the easiest solution caused issues in LX hotspots (mostly yards and ports areas). So I temporarily fixed this locally by assigning an extra tag to level crossings on main and branch lines. This allowed me to  display them at a high zoom level, with those on other line types showing up later. Crossings show up even later. This seems to work really well (at least in my area) and could be worth a discussion.

The only real issue I still have in this regard is that location pins and names overlap, which I'd rather not have. Couldn't find a way to change this rendering order yet...
 
<img width="2318" height="1956" alt="Image" src="https://github.com/user-attachments/assets/411f3847-3d88-42b3-87dd-6068e996f242" />

<img width="2809" height="1674" alt="Image" src="https://github.com/user-attachments/assets/a973d2f0-e4bd-46a2-8697-7e893760b61c" />

<img width="2468" height="1406" alt="Image" src="https://github.com/user-attachments/assets/61603f98-41fa-4541-b264-a0a6427e06e6" />

<img width="87" height="81" alt="Image" src="https://github.com/user-attachments/assets/5b02423e-f317-4250-ad8f-e0b25df7f3f5" />

<img width="107" height="63" alt="Image" src="https://github.com/user-attachments/assets/25d6392a-93e8-4b53-881d-295af024e8e3" />

**Comment by MatisseBE** [comment]
@hiddewie Would you mind reopening this issue, or should I create a new issue? It very likely to get lost otherwise.

**Comment by hiddewie** [comment]
@MatisseBE thanks for the suggestions. A new issue with some specific things to improve is always good.

**Comment by hiddewie** [comment]
> Could it be considered to show a level crossing's reference on the map, and not just in the pop-up? If anyone can help point me towards the right file, that would also be wonderful!!

In summary, the file https://github.com/hiddewie/OpenRailwayMap-vector/blob/master/proxy/js/styles.mjs contains the code to generate the styles for all the layers.

The (level) crossings are defined as POI (places of interest), https://github.com/hiddewie/OpenRailwayMap-vector/blob/9ee474316130aee6517778fa6bf540f38f6fdcf0/features/poi.yaml#L260-L294.

The actual rendering is in the layer `railway_symbols_colored` in https://github.com/hiddewie/OpenRailwayMap-vector/blob/9ee474316130aee6517778fa6bf540f38f6fdcf0/proxy/js/styles.mjs#L2789-L2830, which renders the colored POI icons.

It actually has `text-field` with the ref, so its not entirely clear to me why the reference of the crossings are not shown.
