### ISSUE TITLE
Disable map rotation

### ISSUE THREAD

**Issue by hiddewie** [hiddewie/OpenRailwayMap-vector#56]

**Comment by apriljunge** [comment]
Why you want to disable it?
It could be very useful when orientating on images / videos etc.

**Comment by hiddewie** [comment]
Thanks for your feedback. The map will show the compass control, so the map can be rotated and also restored to the north view.

![image](https://github.com/hiddewie/OpenRailwayMap-vector/assets/1073881/fa702010-8317-449e-8902-97ff7856d280)
