### ISSUE TITLE
Render vacancy detection

### ISSUE THREAD

**Issue by apriljunge** [hiddewie/OpenRailwayMap-vector#63]
It would be really nice to have vacancy detection rendered on the train protection layer

**Comment by hiddewie** [comment]
Thanks, great idea. In general quite some of the interesting and tagged features from https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging are missing.

**Comment by hiddewie** [comment]
https://github.com/hiddewie/OpenRailwayMap-vector/pull/65 renders 2 types of vacancy detection, and also lubricators (mapped in Poland).
