### ISSUE TITLE
Milestone labels shadow more relevant information

### ISSUE THREAD

**Issue by r11r** [hiddewie/OpenRailwayMap-vector#93]
While it is very nice to have Milestone labels on the map, their render priority is a bit too high.

The two screenshots are taken at the same location with a zoom level of roughly 9 and 10. At level 9, Station names and line numbers are visible, at level 10, milestones shadow everything. This problem also exists on higher zoom levels on German lines, where milestones exist every 200m.

I know that there is an algorithm to determin the relevance of a train station, to counter the same problem with close-by station names station names, maybe milestones can be treated as stations with least priority?

![Zoom-Level 9](https://github.com/user-attachments/assets/296f7edf-b7f3-43f6-a7f6-98018b4fcaa4)
![Zoom-Level 10](https://github.com/user-attachments/assets/76c0dc17-3c00-41aa-baf9-e50ffff9cf31)

**Comment by hiddewie** [comment]
Thanks, good point. I am working on solving this. It has to do with a difference in the ordering how lines/symbols versus text are rendered on the map.

**Comment by hiddewie** [comment]
This should be fixed by #97
