### ISSUE TITLE
Format `railway:position` mile values

### ISSUE THREAD

**Issue by wolfy1339** [hiddewie/OpenRailwayMap-vector#94]
when tagging the position of railway points, like milestones, currently in the code it assume a kilometer value, while in the real world, miles are used as well.

Example,
`railway:position=mi:123.45`

It would be nice to transform these values into more user friendly values.

Currently, it renders like so

![image](https://github.com/user-attachments/assets/f23caf2f-6e1c-48d0-889e-224c6728a915)

**Comment by hiddewie** [comment]
Thanks!

Should be fixed after #96
